### ISSUE TITLE
[BUG] Not access to heroku postgresql

### ISSUE THREAD

**Issue by stackdev19** [vencake/resume#3]
`2022-06-04T22:34:20.785787+00:00 app[web.1]: [server] [31m[Nest] 186  - [39m06/04/2022, 10:34:20 PM [31m  ERROR[39m [38;5;3m[ExceptionHandler] [39m[31mno pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "xxxxxxxxxx", database "xxxxxxxxxxxxxx", no encryption[39m
2022-06-04T22:34:20.785948+00:00 app[web.1]: [server] error: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "xxxxxxxxxxxxx", database "xxxxxxxxxxxxxx", no encryption
2022-06-04T22:34:20.785949+00:00 app[web.1]: [server]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
2022-06-04T22:34:20.785949+00:00 app[web.1]: [server]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
2022-06-04T22:34:20.785949+00:00 app[web.1]: [server]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
2022-06-04T22:34:20.785950+00:00 app[web.1]: [server]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2022-06-04T22:34:20.785950+00:00 app[web.1]: [server]     at Socket.emit (node:events:527:28)
2022-06-04T22:34:20.785950+00:00 app[web.1]: [server]     at addChunk (node:internal/streams/readable:315:12)
2022-06-04T22:34:20.785951+00:00 app[web.1]: [server]     at readableAddChunk (node:internal/streams/readable:289:9)
2022-06-04T22:34:20.785951+00:00 app[web.1]: [server]     at Socket.Readable.push (node:internal/streams/readable:228:10)
2022-06-04T22:34:20.785951+00:00 app[web.1]: [server]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2022-06-04T22:34:21.642606+00:00 app[web.1]: [server] error Command failed with exit code 1.`

**Comment by stackdev19** [comment]
How can I solve it?

**Comment by rjholo** [comment]
Add environmental variable as following:
`PGSSLMODE=no-verify`
